#ifndef SATORI_X11ERROR_HPP
#define SATORI_X11ERROR_HPP

#define XERR_SUCCESS 0
#define XERR_BAD_REQUEST 1
#define XERR_BAD_VALUE 2
#define XERR_BAD_WINDOW 3
#define XERR_BAD_PIXMAP 4
#define XERR_BAD_ATOM 5
#define XERR_BAD_CURSOR 6
#define XERR_BAD_FONT 7
#define XERR_BAD_MATCH 8
#define XERR_BAD_DRAWABLE 9
#define XERR_BAD_ACCESS 10
#define XERR_BAD_ALLOC 11
#define XERR_BAD_COLORMAP 12
#define XERR_BAD_GC 13
#define XERR_BAD_ID_CHOICE 14
#define XERR_BAD_NAME 15
#define XERR_BAD_LENGTH 16
#define XERR_BAD_IMPL 17

#endif

